import { FormSchema } from '../components/form/DynamicForm';

export const PROFILE_SCHEMA: FormSchema = {
  name: { type: 'input', label: 'Your name, as you like to be known:', value: '' },
  id: 'sub' as any,
  profile_image: {
    type: 'image',
    label: "Profile Picture (be sure to click the upload icon):",
    src: '',
  } as any,
  urls: {
    type: 'editable_input_array',
    label: 'Do you have any social media or other interesting links to share (ex. https://ic.org/directory/..)?',
    value: [],
  } as any,
  transhumanist_ideas: {
    type: 'editor',
    label: 'What transhumanist ideas do you want to work on together and test for their efficacy? (ex: quantum entanglement, testing or refuting current claims of telepathy; use of an array of interconnected assembloids as an organic living server that interfaces with an EEG/TMS system, extra…)',
    value: '',
  } as any,
  crazy_ideas: { type: 'editor', label: 'What crazy ideas do you have?', value: '' } as any,
  video_series: {
    type: 'radio',
    label: 'Would you be interested in participating in a video series?',
    value: ['Yes', 'No', 'Maybe'],
  } as any,
  wants: {
    type: 'slider_group',
    label: 'How much do these social qualities factor into the search for a community?',
    other: { label: 'Something else:', value: '' },
    items: {
      deep_conver: { label: 'Deep conversation', value: 50 },
      shared_challenges: { label: 'Shared challenges', value: 50 },
      shared_passions: { label: 'Shared passions', value: 50 },
      shared_personality: { label: 'Shared personality', value: 50 },
      shared_skills: { label: 'Shared skills and knowledge', value: 50 },
      physical_closeness: { label: 'Physical closeness/touch between people', value: 50 },
      complementary_skills: { label: 'Complementary skills and knowledge', value: 50 },
      different_challenges: { label: 'Different challenges', value: 50 },
      different_passions: { label: 'Different passions', value: 50 },
      range_of_personalities: { label: 'A range of personalities', value: 50 },
      separate_personal_space: { label: 'Separate personal space', value: 50 },
      common_spaces: { label: 'Common spaces that people naturally regularly convene in', value: 50 },
      set_structured_time: { label: 'Set structured time together (i.e. planned events/meetings or community dinners)', value: 50 },
    },
  } as any,
  skills: {
    type: '2_slider_group',
    label: 'What skills do you currently have or want to acquire more of?',
    other: { label: 'Something else:', value: '' },
    items: {
      ai_machine_learning: { label: 'AI and Machine Learning', have: 50, want: 50 },
      bioengineering: { label: 'Bioengineering', have: 50, want: 50 },
      business: { label: 'Business', have: 50, want: 50 },
      community_building: { label: 'Community Building', have: 50, want: 50 },
      electronics: { label: 'Electronics', have: 50, want: 50 },
      medicine: { label: 'Medicine', have: 50, want: 50 },
      robotics: { label: 'Robotics', have: 50, want: 50 },
      microbiology: { label: 'Microbiology', have: 50, want: 50 },
      neuroscience: { label: 'Neuroscience', have: 50, want: 50 },
      education: { label: 'Teaching/Learning', have: 50, want: 50 },
      government: { label: 'Government', have: 50, want: 50 },
      quantum_physics: { label: 'Quantum physics', have: 50, want: 50 },
      construction: { label: 'Sustainable construction', have: 50, want: 50 },
    },
  } as any,
  sharing: {
    type: 'slider_group',
    label: 'Are you comfortable sharing (Multiple people in the same location at the same time or using the same thing, possibly at different times):',
    other: { label: 'Something else:', value: '' },
    items: {
      food: { label: 'Food', value: 50 },
      a_kitchen: { label: 'A kitchen', value: 50 },
      dishes_utensils: { label: 'Dishes/utensils', value: 50 },
      appliances: { label: 'Appliances', value: 50 },
      a_computer_laptop: { label: 'A computer/laptop', value: 50 },
      smartphone: { label: 'A smartphone', value: 50 },
      cloths: { label: 'Clothes', value: 50 },
      shop_lab_equipment: { label: 'Shop/Lab equipment', value: 50 },
      consumable_materials: { label: 'Consumable materials (ex. TP, soap, cleaning supplies)', value: 50 },
      house: { label: 'A house', value: 50 },
      bedroom: { label: 'A bedroom', value: 50 },
      bathroom: { label: 'A bathroom', value: 50 },
      shower: { label: 'A shower', value: 50 },
      bed: { label: 'A Bed', value: 50 },
      a_life: { label: 'A Life Together', value: 50 },
    },
  } as any,
  current_location: {
    type: 'map',
    label: 'Your current Location (can be as general or specific as you like)',
    placed: 'False',
    coordinates: { lat: 42.3676371, lng: -72.5054855 },
  } as any,
  potential_locations: {
    type: 'editor',
    label: 'Do you know any locations that we should check out as a possible location where we could start working on things together in person?',
    value: '',
  } as any,
};
